config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'categories/index'
  get 'categories/show'
  get 'responses/create'
  root 'static_pages#home'
  get 'static_pages/help'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :topics, only: %i(show index create)
  resources :responses, only: [:create]
  resources :categories, only: [:show]
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    if user.try(:admin?)
      can :access, :rails_admin
      can :manage, :all
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :relationships
  has_many :topics, through: :relationships

  validates :title, presence: true, length: { maximum: 64 }, uniqueness: true
  validates :content, presence: true, length: { maximum: 256 }
end

app/models/relationship.rb
# frozen_string_literal: true

class Relationship < ApplicationRecord
  belongs_to :category
  belongs_to :topic

  validates :category_id, presence: true
  validates :topic_id, presence: true
end

app/models/response.rb
# frozen_string_literal: true

class Response < ApplicationRecord
  belongs_to :user
  belongs_to :topic

  validates :user_id, presence: true
  validates :topic_id, presence: true
  validates :content, presence: true, length: { maximum: 1024 }
end

app/models/topic.rb
# frozen_string_literal: true

class Topic < ApplicationRecord
  belongs_to :user
  has_many :responses, dependent: :destroy
  has_many :relationships
  has_many :categories, through: :relationships

  default_scope -> { order(created_at: :desc) }

  validates :title, presence: true, length: { maximum: 64 }
  validates :user_id, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :topics
  has_many :responses
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Validation
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
  before_action :authenticate_user!, only: [:show]

  def show
    @categories = Category.all
    @category = Category.find(params[:id])
    @topics = @category.topics.includes([:relationships]).includes([:categories]).paginate(page: params[:page], per_page: 5)
  end
end

app/controllers/responses_controller.rb
# frozen_string_literal: true

class ResponsesController < ApplicationController
  before_action :authenticate_user!, only: [:create]

  def create
    @response = current_user.responses.build(response_params)

    redirect_to request.referrer || root_url if @response.save
  end

  private

  def response_params
    params.require(:response).permit(:content, :topic_id, :poster)
  end
end

app/controllers/static_pages_controller.rb
# frozen_string_literal: true

class StaticPagesController < ApplicationController
  before_action :authenticate_user!, only: [:home]

  def home
    @topics = Topic.all.includes([:relationships]).includes([:categories]).paginate(page: params[:page], per_page: 5)
    @categories = Category.all
  end
end

app/controllers/topics_controller.rb
# frozen_string_literal: true

class TopicsController < ApplicationController
  before_action :authenticate_user!, only: %i(create index show search)
  require 'will_paginate/array'

  # POST /topics
  def create
    @topic_form = TopicForm.new(new_topic_form_params)
    redirect_to topic_path(@topic_form.topic_id) if @topic_form.save!
  end

  # GET /topic/:id
  def show
    @categories = Category.all
    @topic = Topic.find(params[:id])
    @responses = @topic.responses.includes([:user])
  end

  # GET /topics
  def index
    @categories = Category.all
    @keyword = params[:keyword]
    @topics = Topic.where('title like ?', "%#{params[:keyword]}%").includes([:relationships]).includes([:categories])
    @responses = Topic.joins(:responses).where('content like ?', "%#{params[:keyword]}%").includes([:relationships]).includes([:categories])
    @results = @topics | @responses
    @results = @results.paginate(page: params[:page], per_page: 5)
  end

  private

  def new_topic_form_params
    params.permit(:title, :content, :poster, category_ids: []).merge(user_id: current_user.id)
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/categories_helper.rb
# frozen_string_literal: true

module CategoriesHelper
end

app/helpers/responses_helper.rb
# frozen_string_literal: true

module ResponsesHelper
end

app/helpers/static_pages_helper.rb
# frozen_string_literal: true

module StaticPagesHelper
end

app/helpers/topics_helper.rb
# frozen_string_literal: true

module TopicsHelper
end

app/views/layouts/_flash.html.erb
<div class="container">
  <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "#{key}") %>
   <% end %>
 </div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="container">
    <%= link_to "掲示板", root_path, class: "nav-logo" %>
    <nav class="nav navbar-right flex">
      <% if user_signed_in? %>
        <%= render 'layouts/search_form' %>
        <%= link_to "ユーザー情報編集", edit_user_registration_path(current_user), class: "nav-link" %>
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link" %>
      <% end %>
    </nav>
  </div>
</header>

app/views/layouts/_search_form.html.erb
<%= form_with url: topics_path, method: :get, local: true do |form| %>
  <%= form.text_field :keyword, placeholder: "スレッド・レスを検索" %>
  <%= form.submit "検索" %>
<% end %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/_sidemenu.html.erb
<% if user_signed_in? %>
  <div class="col-md-2 col-sm-2 col-xs-12 sidemenu">
    <h2>カテゴリ一覧</h2>
    <% categories.each do |category| %>
      <%= link_to category.title, category_path(category), class: "menu-category" %>
    <% end %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title> 
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container-fluid">
      <div class="row">
        <%= render 'layouts/flash' %>
        <%= yield %>
      </div>
    </div>
    <%= render 'layouts/footer', class: "footer" %>
  </body>
</html>

app/views/shared/_response_form.erb
<div class="response-form">
  <%= form_with model: Response.new do |form| %>
    <div class="field">
      <div>
      　名前
        <%= form.text_field :poster, placeholder: "名無し", class: "form-control" %>
      </div>
      <div>
      　投稿
        <%= form.text_area :content, class: "form-control response-form__content"  %>
      </div>
    </div>
    <div class="btn">
      <%= form.submit "投稿" , class: "btn-lg" %>
    </div>
    <%= form.hidden_field :topic_id, value: topic.id %>
  <% end %>
</div>
  

app/views/shared/_topic_form.erb
<div class="topic-form">
  <%= form_with method: :post, url: topics_path do |form| %>
    <div class="field">
      <div>
      　スレッドタイトル(必須)
        <%= form.text_field :title, class: "form-control" %>
      </div>
      <div>
      　名前
        <%= form.text_field :poster, placeholder: "名無し", class: "form-control" %>
      </div>
      <div>
      　投稿（必須）
        <%= form.text_area :content, class: "form-control topic-form__content" %>
      </div>
      <div class="checkbox">
        カテゴリ（必須）：<%= form.collection_check_boxes :category_ids, Category.all, :id, :title, class: "form-controlx" %>
      </div>
    </div>
    <div class="btn">
      <%= form.submit "スレッドを作成", class: "btn-lg" %>
    </div>
  <% end %>
</div>
  